name: GitHub Actions Artifact Demo
run-name: ${{ github.actor }} is testing out GitHub Artifact
on: [ push ]
jobs:
  Explore-GitHub-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - run: echo "# Artifacts and results output demos" >> $GITHUB_STEP_SUMMARY
      - name: Store mock file
        uses: actions/upload-artifact@v4
        with:
          name: mock-jmh-report
          path: .resources/mock-jmh-results.json
      - name: Set environment variable
        run: |
          echo 'MOCK_JSON<<EOF' >> $GITHUB_ENV
          cat .resources/mock-jmh-results.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Show Json in $GITHUB_STEP_SUMMARY
        run: |
          echo "## Mock Json content from env property" >> $GITHUB_STEP_SUMMARY
          echo ""
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo "${{env.MOCK_JSON}}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - run: echo "## Mock Json content directly from file" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat .resources/mock-jmh-results.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
