name: GitHub Actions Artifact Demo
run-name: ${{ github.actor }} is testing out GitHub Artifact
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "## Hello Summary World" >> $GITHUB_STEP_SUMMARY
      - name: Store mock file
        uses: actions/upload-artifact@v4
        with:
          name: mock-jmh-report
          path: .resources/mock-jmh-results.json